### PR TITLE
7 not able to enter programming mode

### LINKED ISSUE #7: Not able to enter programming mode on EMH meter - serial transport
After checking some errors reported by users, #4 I found that it is not possible to enter programming mode on an EMH meter. 

A quick look suggests it is a combined error of the ASCII representation of a command and that we are not preforming a baudrate switch that the meter proposes. (Or telling the meter that we want to stay at our current baudrate.) 

The baudrate issue is only contained to the serial transport as it doesn't have effect on the TCP transport. But the client still needs to call the switch for both of the transport to work.

### PR DESCRIPTION
**Pull request by Krolken**
Fixes issues in connection to standard IEC 62056-21 meters, Fixes #7 and #8 .

### CODE REVIEW

**Comment by arkjotgreen** [comment]
Hi Krolken, I have a question, I am trying with my application and your library to read the value from an energy meter (Itron model SL7000).
When trying to connect, a "Pipe Broken" error is generated. I don't understand where the problem is. I  post the code. Thanks so much!

```
from iec62056_21.client import Iec6205621Client

client = Iec6205621Client.with_tcp_transport(address=('192.168.0.7', 4001),
                                                         device_address='17',
                                                         password='00000000')

client.connect()
client.standard_readout()
client.disconnect()

```

**Comment by arkjotgreen** [comment]
Hi Krolken, I have a question, I am trying with my application and your library to read the value from an energy meter (Itron model SL7000).
When trying to connect, a "Pipe Broken" error is generated. I don't understand where the problem is. I  post the code. Thanks so much!

```
from iec62056_21.client import Iec6205621Client

client = Iec6205621Client.with_tcp_transport(address=('192.168.0.7', 4001),
                                                         device_address='17',
                                                         password='00000000')

client.connect()
client.standard_readout()
client.disconnect()

```

**Comment by Krolken** [comment]
@arkjotgreen could you create an issue and also post the debug output from your program.

**Comment by arkjotgreen** [comment]
`$ testReadDLMSProt.py:10: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('172.18.0.3', 52940), raddr=('192.168.0.7', 4001)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback`

The compiler to stop over "client.standard_readout()", it's waiting for 20-30sec and generate this message.

Ok sorry i have testing this code with unittest, but without it, used a simple file with call function it's generate this output, always to this istruction  `client.standard_readout() `:

[Errno 32] Broken pipe

**Pull request merged**
